
import type { Metadata } from "next";
//import { Inter } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/components/navbar_old";
import { SectionHero } from "@/components/section-hero";
import { Info } from "@/components/info";
import { WhatsAppButton } from "@/components/whatsapp";
import { SocialMediaButtons } from "@/components/social-media";
import { About } from "@/components/about";
import { Systems } from "@/components/systems";
import { Brands } from "@/components/brands";
import { News } from "@/components/news";
import { Contact } from "@/components/contact";
import { Footer } from "@/components/footer";
import { Testimonial } from "@/components/testimonials";
import { MenuMobile } from "@/components/navbar";

export const metadata: Metadata = {
  title: "Adaline",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    
    <html lang="en">
      <body className={`bg-white mt-3 `} >
        <MenuMobile/> 
        <SectionHero/>
        <WhatsAppButton/>
        <SocialMediaButtons/>
        <Info/>
        <About/>
        <Systems/>
        <Testimonial/>
        <Brands/>
        <News/>
        <Contact/>
        <Footer/>
      </body>
    </html>
  );
}
